steps:
- name: 'gcr.io/cloud-builders/gradle'
  id: 'SpotBugs'
  args: ['spotbugsTest', 'spotbugsMain']
- name: 'gcr.io/cloud-builders/gradle'
  id: 'Tests'
  args: ['test']
- name: 'gcr.io/$PROJECT_ID/sonar-scanner:latest'
  entrypoint: 'bash'
  args:
    - '-c'
    - '/launch.sh'
    - '-Dsonar.host.url=https://sonarcloud.io'
    - '-Dsonar.login=$$SONAR_TOKEN'
    - '-Dsonar.projectKey=VerkhovtsovPavel_mock-service'
    - '-Dsonar.organization=verkhovtsovpavel'
    - '-Dsonar.sources=.'
  secretEnv: ['SONAR_TOKEN']
availableSecrets:
  secretManager:
    - versionName: projects/83509940274/secrets/SONAR_TOKEN/versions/2
      env: 'SONAR_TOKEN'