steps:
- name: 'gcr.io/cloud-builders/gradle'
  args: ['gradle spotbugsTest spotbugsMain']
- name: 'gcr.io/cloud-builders/gradle'
  args: ['gradle test']
- name: 'gcr.io/cloud-builders/gradle'
  entrypoint: 'bash'
  args:
    - -c
    - gradle sonarqube -DSONAR_TOKEN=$$SONAR_TOKEN
  secretEnv: ['SONAR_TOKEN']
availableSecrets:
  secretManager:
    - versionName: projects/83509940274/secrets/SONAR_TOKEN/versions/1
      env: 'SONAR_TOKEN'