steps:
- name: 'gradle:5.6.2-jdk11'
  id: 'SpotBugs'
  args: ['spotbugsTest', 'spotbugsMain']

- name: 'gradle:5.6.2-jdk11'
  id: 'Tests'
  args: ['test']

- name: 'gradle:5.6.2-jdk11'
  id: 'SonarQube'
  entrypoint: 'bash'
  args:
    - -c
    - gradle sonarqube -Dsonar.login=$$SONAR_TOKEN
  secretEnv: ['SONAR_TOKEN']
availableSecrets:
  secretManager:
    - versionName: projects/83509940274/secrets/SONAR_TOKEN/versions/2
      env: 'SONAR_TOKEN'
