steps:
- name: 'gradle:5.6.2-jdk11'
  id: 'SpotBugs'
  entrypoint: 'bash'
  args: ['-c', 'gradle', 'spotbugsTest', 'spotbugsMain']

- name: 'gradle:5.6.2-jdk11'
  id: 'Unit Tests'
  entrypoint: 'bash'
  args: ['-c', 'gradle', 'test', '--tests "by.pavel.mock.unit.*"']

- name: 'gradle:5.6.2-jdk11'
  id: 'SonarQube'
  entrypoint: 'bash'
  args:
    - -c
    - gradle sonarqube -Dsonar.login=$$SONAR_TOKEN
  secretEnv: ['SONAR_TOKEN']

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: 'Deploy'
  entrypoint: 'bash'
  args: ['-c', 'gcloud config set app/cloud_build_timeout 1600 && gcloud app deploy build.gradle']

- name: 'gradle:5.6.2-jdk11'
  id: 'API Tests'
  entrypoint: 'bash'
  args: ['-c', 'gradle', 'test', '--tests "by.pavel.mock.api.*"']

timeout: '1600s'
availableSecrets:
  secretManager:
    - versionName: projects/83509940274/secrets/SONAR_TOKEN/versions/2
      env: 'SONAR_TOKEN'